### ISSUE TITLE
Misunderstanding of the function's operation (UKR-localization)

### ISSUE THREAD

**Issue by evd316** [ajayyy/ExtensionTranslations#59]
Hi, ajayyy!
I'm confused, can't translate correctly with context and don't understand the actions of the functions, some of which **duplicate** the result:

Title Case
Identifier (Key): TitleCase "З великої літери"
…

Sentence Case
Identifier (Key): SentenceCase "Як у реченнях"
…

Lower Case
Identifier (Key): LowerCase "Нижній Регістр"
…

First Letter Uppercase
Identifier (Key): FirstLetterUppercase "Перша Буква Великою"
…

Capitalize Words
Identifier (Key): CapitalizeWords "Слова З Великої Літери"
…

Please, provide examples for each function to see the difference between them.

**Comment by ajayyy** [comment]
these functions are options in the DeArrow extension for automatically changing the formatting of YouTube titles

![image](https://github.com/user-attachments/assets/d0bf11c1-9e7f-440c-b61a-12f440f0adf5)

**Comment by evd316** [comment]
### As I understood:

**Sentence Case**
_Як у реченнях. Як у реченнях._

**Lower Case**
_малі літери. малі літери._

**First Letter Uppercase**
_Перша буква великою. перша буква великою._

**Capitalize Words**
_Слова З Великої Літери. Слова З Великої Літери._

What does the '**Title Case**' do?

**Comment by ajayyy** [comment]
Title case is really meant for English and not enabled by default for people without English as their set language.

It leaves certain words lower case such as "with" and "for" while leaving others capitalized

You can read more about it here: https://apastyle.apa.org/style-grammar-guidelines/capitalization/title-case

**Comment by evd316** [comment]
Yes, thank you, I already understood everything and translated accordingly.
